# Generated by Django 5.0.6 on 2024-05-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_tunes_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunes',
            name='author',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
