# Generated by Django 5.0.6 on 2024-05-30 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_tunes_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('info', models.TextField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('audio', models.FileField(upload_to='music')),
                ('pic', models.FileField(upload_to='music')),
            ],
        ),
        migrations.CreateModel(
            name='SongResposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('info', models.TextField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('audio', models.FileField(upload_to='music')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.songs')),
            ],
        ),
    ]
