# Generated by Django 5.0.6 on 2024-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_songs_songresposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='songresposes',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
