# Generated by Django 5.0.6 on 2024-06-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_alter_songresposes_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songresposes',
            name='volumeOffset',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
