# Generated by Django 5.0.6 on 2024-06-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_songresposes_checked_songresposes_modcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='songresposes',
            name='demoCreated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
