# Generated by Django 5.0.6 on 2024-06-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_songresposes_democreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songresposes',
            name='audio',
            field=models.FileField(upload_to='music/collab_responses'),
        ),
    ]
